load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "type_traits",
  hdrs = [ 
    "is_container.h",
    "type_traits.h",
  ],
  deps = ["//common/include:top"],
  visibility = ["//visibility:public"],
)


