load("@rules_cc//cc:defs.bzl", "cc_test", "cc_library")

cc_library(
  name = "type_traits",
  hdrs = [ 
  "is_container.h",
  "type_traits.h",
  ],
  srcs = [],
  visibility = ["//visibility:public"],
)


