load("@rules_cc//cc:defs.bzl", "cc_test", "cc_library")

cc_library(
  name = "utils",
  hdrs = ["utils.h"],
  srcs = ["utils.cpp"],
  deps = ["//blockchain/common/type_traits:type_traits"],
  visibility = ["//visibility:public"],
)



