load("@rules_cc//cc:defs.bzl", "cc_library")

cc_binary(
  name = "encrypt",
    srcs = ["encrypt.cpp"],
    deps = ["//utils/getopt:getopt_impl"],
    visibility = ["//visibility:public"],
)

